---
application:
  name: "docusaurus"
  project: "random"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "db"
  version: "10"
routers:
- name: "main-docusaurus"
  routes:
  - application_name: "docusaurus"
    paths:
    - "/*"
