name: Build Performance

on:
  # Note! you can't safely use "pull_request_target" here
  # This workflow is mostly useful for "internal PRs"
  # External PRs won't be able to post a PR comment
  # See https://github.com/preactjs/compressed-size-action/issues/54
  # See https://securitylab.github.com/research/github-actions-preventing-pwn-requests
  pull_request:
    branches:
      - main
    paths-ignore:
      - website/docs/**

jobs:
  build-size:
    name: Build Size Report
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3 https://api.github.com/repos/actions/checkout/git/tags/b0e28b5ac45a892f91e7d036f8200cf5ed489415
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # v3 https://api.github.com/repos/actions/setup-node/git/commits/9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: '16'
          cache: yarn
      - uses: preactjs/compressed-size-action@8119d3d31b6e57b167e09c81dfa877eada3bcb35 # v2 https://api.github.com/repos/preactjs/compressed-size-action/git/commits/8119d3d31b6e57b167e09c81dfa877eada3bcb35
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: build:website:en
          clean-script: clear:website # see https://github.com/facebook/docusaurus/pull/6838
          pattern: '{website/build/assets/js/main*js,website/build/assets/css/styles*css,website/.docusaurus/globalData.json,website/build/index.html,website/build/blog/index.html,website/build/blog/**/introducing-docusaurus/*,website/build/docs/index.html,website/build/docs/installation/index.html,website/build/tests/docs/index.html,website/build/tests/docs/standalone/index.html}'
          strip-hash: '\.([^;]\w{7})\.'
          minimum-change-threshold: 30
          compression: none
  build-time:
    name: Build Time Perf
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3 https://api.github.com/repos/actions/checkout/git/tags/b0e28b5ac45a892f91e7d036f8200cf5ed489415
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # v3 https://api.github.com/repos/actions/setup-node/git/commits/9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          cache: yarn
      - name: Installation
        run: yarn

      # Ensure build with a cold cache does not increase too much
      - name: Build (cold cache)
        run: yarn workspace website build --locale en
        timeout-minutes: 8

      # Ensure build with a warm cache does not increase too much
      - name: Build (warm cache)
        run: yarn workspace website build --locale en
        timeout-minutes: 2
    # TODO post a Github comment with build with perf warnings?
