name: Build Size Report

on:
  pull_request_target:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Navigate to website directory
        run: cd website
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          pattern: '{build/main*js,build/styles*css,build/index.html,build/blog/**/introducing-docusaurus/*,build/docs/introduction/index.html}'
          strip-hash: '\.([^;]\w{7})\.'
          minimum-change-threshold: 100
