name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn
      - name: Installation
        run: yarn install --immutable
      - name: Lint
        run: |
          echo "::add-matcher::.github/workflows/cspell-problem-matcher.json"
          yarn lint:ci
      - name: Prettier Code
        run: yarn format:diff
