name: Migration CLI

on:
  pull_request:
    branches:
      - master
    paths:
      - packages/docusaurus-migration/**
      - website-1.x/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Installation
        run: yarn
      - name: Migrate D1 website
        run: yarn test:v1Migration:migrate
      - name: Build D1 migrated website
        run: yarn test:v1Migration:build
        env:
          CI: true
