name: Showcase Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - website/src/data/**

jobs:
  validate-config:
    name: Validate Showcase Config
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
      - name: Installation
        run: yarn
      - name: Resize Images
        run: |
          node admin/scripts/image-resize.mjs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Resize image'
          git push
      - name: Test
        run: yarn test website/src/data/__tests__/user.test.ts
