name: Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - website/**

jobs:
  test:
    name: Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '17']
    steps:
      - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3 https://api.github.com/repos/actions/checkout/git/tags/b0e28b5ac45a892f91e7d036f8200cf5ed489415
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # v3 https://api.github.com/repos/actions/setup-node/git/commits/9ced9a43a244f3ac94f13bfd896db8c8f30da67a
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Installation
        run: yarn
      - name: Test
        run: yarn test
      - name: TypeCheck website
        run: yarn workspace website typecheck
