name: V2 Build Blog-only

on:
  pull_request:
    branches:
      - main
    paths:
      - "website-1.x/blog/**"
      - "packages/docusaurus/**"

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - name: Installation
        with:
          install-command: yarn
        run: npm ci
      - name: Build blog-only
        run: yarn workspace website build:blogOnly
