name: V2 Tests E2E

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'website-1.x/**'
      - 'packages/docusaurus-1.x/**'
      - 'packages/docusaurus-init-1.x/**'

jobs:
  yarn-v1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Installation
        run: yarn
      - name: Setup test-website project against master release
        run: |
          yarn test:build:v2
          rm -rf node_modules
      - name: Start test-website project
        run: cd test-website && yarn start --no-open
        env:
          E2E_TEST: true
      - name: Build test-website project
        run: cd test-website && yarn build
        env:
          CI: true
  yarn-v2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Installation
        run: yarn
      - name: Setup test-website project against master release
        run: |
          KEEP_CONTAINER=true yarn test:build:v2
          rm -rf node_modules
      - name: Setup test-website project for Yarn v2
        run: |
          cd test-website
          yarn set version berry
          yarn config set pnpMode loose
          yarn config set npmRegistryServer http://localhost:4873
          yarn config set unsafeHttpWhitelist --json '["localhost"]'
          yarn config set enableGlobalCache true
          yarn install
      - name: Start test-website project
        run: cd test-website && yarn start --no-open
        env:
          E2E_TEST: true
      - name: Build test-website project
        run: cd test-website && yarn build
        env:
          CI: true
